---
deployment:
  tasks:
    - /usr/local/bin/ea-php82 /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/ea-php82 artisan optimize:clear
    - /bin/mkdir -p database
    - /bin/touch database/database.sqlite
    - /usr/local/bin/ea-php82 artisan migrate --force
    - /usr/local/bin/ea-php82 artisan storage:link
